### ISSUE TITLE
Issues with various Archived Projects pages

### ISSUE THREAD

**Issue by GentrySteven** [DLFMetadataAssessment/Sandbox#277]
For the main [Archived/Completed Projects page](https://dlfmetadataassessment.github.io/projects-archived):

- [x] Reduce hyperlinked text to just the bolded words.
- [x] Update some text re: when certain projects were undertaken, since some of them say things like "under review".
- [x] Move the "Benchmarks Survey" list item to  the 'Current' Projects page. This fix would also address one of Hannah's [issues on the production site](https://github.com/DLFMetadataAssessment/DLFMetadataAssessment.github.io/issues/129).

For each sub-page associated with the [Archived/Completed Projects page](https://dlfmetadataassessment.github.io/projects-archived):

- [x] Update and/or create the breadcrumbs, since they only point to the "Projects" page. This fix would also address Gabi's [issue on the production site](https://github.com/DLFMetadataAssessment/DLFMetadataAssessment.github.io/issues/103).

For specific subpages:

- [x] On the [Environmental Scan page](https://dlfmetadataassessment.github.io/environmental-scan), fix miscellaneous broken links and typographical errors. 

- [x]  On the [Metadata Quality Benchmarks](https://dlfmetadataassessment.github.io/Sandbox/benchmarks), fix the "Anonymized data" broken link. This fix would also address one of Hannah's [issues on the production site](https://github.com/DLFMetadataAssessment/DLFMetadataAssessment.github.io/issues/121).

- [x] On the [Metadata Analysis Workshop page](https://dlfmetadataassessment.github.io/Sandbox/metadata-workshop), add spaces to "DLFForum2017"

**Comment by GentrySteven** [comment]
The breadcrumbs issue described above is now a non-issue due to the site redesign.
